import streamlit as st
import geopandas as gpd
from shapely.geometry import box, mapping
from shapely.ops import unary_union
from pyproj import CRS
import math
from lxml import etree
from streamlit_folium import st_folium
import folium
import tempfile
from datetime import datetime
from fpdf import FPDF
import os, requests

# -------------------------------------------------
# Streamlit UI setup
# -------------------------------------------------
st.set_page_config(page_title="KML to Grid Generator v3.0", layout="wide")
st.title("🗺️ KML to Grid Generator v3.0")

# -------------------------------------------------
# Initialize session state
# -------------------------------------------------
def init_state():
    if "user_inputs" not in st.session_state:
        st.session_state["user_inputs"] = {
            "range_name": "",
            "rf_name": "",
            "beat_name": "",
            "year_of_work": ""
        }
    if "generated" not in st.session_state:
        st.session_state["generated"] = False

init_state()

# -------------------------------------------------
# CRS helper
# -------------------------------------------------
def utm_crs_for_lonlat(lon, lat):
    zone = int((lon + 180) / 6) + 1
    epsg = 32600 + zone if lat >= 0 else 32700 + zone
    return CRS.from_epsg(epsg)

# -------------------------------------------------
# Generate grid clipped to AOI
# -------------------------------------------------
def make_grid_exact_clipped(polygons_ll, cell_size_m=100):
    merged_ll = unary_union(polygons_ll)
    centroid = merged_ll.centroid
    utm = utm_crs_for_lonlat(centroid.x, centroid.y)

    merged_utm = gpd.GeoSeries([merged_ll], crs=4326).to_crs(utm)
    minx, miny, maxx, maxy = merged_utm.total_bounds
    cols = int(math.ceil((maxx - minx) / cell_size_m))
    rows = int(math.ceil((maxy - miny) / cell_size_m))

    cells = []
    aoi_union = merged_utm.unary_union
    for i in range(cols):
        for j in range(rows):
            x0 = minx + i * cell_size_m
            y0 = miny + j * cell_size_m
            cell = box(x0, y0, x0 + cell_size_m, y0 + cell_size_m)
            if aoi_union.intersects(cell):
                inter = cell.intersection(aoi_union)
                if not inter.is_empty:
                    cells.append(inter)

    cells_ll = [gpd.GeoSeries([c], crs=utm).to_crs(4326).iloc[0] for c in cells]
    return cells_ll, merged_ll

# -------------------------------------------------
# KML coordinate writer helpers
# -------------------------------------------------
def _ring_coords_to_kml(ring):
    coords = [f"{pt[0]},{pt[1]},0" for pt in ring.coords if len(pt) >= 2]
    return " ".join(coords)

def _write_polygon_coords(ns, polygon_elem, geom):
    def write_one(poly):
        outer = etree.SubElement(polygon_elem, f"{{{ns}}}outerBoundaryIs")
        lr_out = etree.SubElement(outer, f"{{{ns}}}LinearRing")
        etree.SubElement(lr_out, f"{{{ns}}}coordinates").text = _ring_coords_to_kml(poly.exterior)
        for hole in getattr(poly, "interiors", []):
            inner = etree.SubElement(polygon_elem, f"{{{ns}}}innerBoundaryIs")
            lr_in = etree.SubElement(inner, f"{{{ns}}}LinearRing")
            etree.SubElement(lr_in, f"{{{ns}}}coordinates").text = _ring_coords_to_kml(hole)
    if geom.geom_type == "Polygon":
        write_one(geom)
    elif geom.geom_type == "MultiPolygon":
        for part in geom.geoms:
            poly_elem = etree.SubElement(polygon_elem.getparent(), f"{{{ns}}}Polygon")
            write_one(part)

# -------------------------------------------------
# Generate grid-only KML
# -------------------------------------------------
def generate_grid_only_kml(cells_ll, merged_ll):
    ns = "http://www.opengis.net/kml/2.2"
    kml = etree.Element(f"{{{ns}}}kml")
    doc = etree.SubElement(kml, f"{{{ns}}}Document")
    etree.SubElement(doc, f"{{{ns}}}name").text = "Grid Only"
    etree.SubElement(doc, f"{{{ns}}}description").text = "Generated by Rasipuram Range"

    style = etree.SubElement(doc, f"{{{ns}}}Style", id="gridStyle")
    ls = etree.SubElement(style, f"{{{ns}}}LineStyle")
    etree.SubElement(ls, f"{{{ns}}}color").text = "ff0000ff"
    etree.SubElement(ls, f"{{{ns}}}width").text = "1"
    ps = etree.SubElement(style, f"{{{ns}}}PolyStyle")
    etree.SubElement(ps, f"{{{ns}}}fill").text = "0"

    for i, cell in enumerate(cells_ll, 1):
        pm = etree.SubElement(doc, f"{{{ns}}}Placemark")
        etree.SubElement(pm, f"{{{ns}}}name").text = str(i)
        etree.SubElement(pm, f"{{{ns}}}styleUrl").text = "#gridStyle"
        poly_elem = etree.SubElement(pm, f"{{{ns}}}Polygon")
        _write_polygon_coords(ns, poly_elem, cell)

    return etree.tostring(kml, pretty_print=True, xml_declaration=True, encoding="UTF-8").decode("utf-8")

# -------------------------------------------------
# Generate labeled + merged KML
# -------------------------------------------------
def generate_labeled_kml(cells_ll, merged_ll, user_inputs, overlay_gdf=None):
    ns = "http://www.opengis.net/kml/2.2"
    kml = etree.Element(f"{{{ns}}}kml")
    doc = etree.SubElement(kml, f"{{{ns}}}Document")
    etree.SubElement(doc, f"{{{ns}}}name").text = "Labeled Grid"
    etree.SubElement(doc, f"{{{ns}}}description").text = "Developed by Rasipuram Range"

    style = etree.SubElement(doc, f"{{{ns}}}Style", id="gridStyle")
    ls = etree.SubElement(style, f"{{{ns}}}LineStyle")
    etree.SubElement(ls, f"{{{ns}}}color").text = "ff0000ff"
    etree.SubElement(ls, f"{{{ns}}}width").text = "1"
    ps = etree.SubElement(style, f"{{{ns}}}PolyStyle")
    etree.SubElement(ps, f"{{{ns}}}fill").text = "0"

    for i, cell in enumerate(cells_ll, 1):
        pm = etree.SubElement(doc, f"{{{ns}}}Placemark")
        etree.SubElement(pm, f"{{{ns}}}name").text = str(i)
        etree.SubElement(pm, f"{{{ns}}}styleUrl").text = "#gridStyle"
        html = f"""<table border="1" cellspacing="0" cellpadding="3">
<tr><td>ID</td><td>{i}</td></tr>
<tr><td>Range</td><td>{user_inputs.get('range_name','')}</td></tr>
<tr><td>RF</td><td>{user_inputs.get('rf_name','')}</td></tr>
<tr><td>Beat</td><td>{user_inputs.get('beat_name','')}</td></tr>
<tr><td>Year</td><td>{user_inputs.get('year_of_work','')}</td></tr></table>"""
        desc = etree.SubElement(pm, f"{{{ns}}}description")
        desc.text = etree.CDATA(html)
        poly_elem = etree.SubElement(pm, f"{{{ns}}}Polygon")
        _write_polygon_coords(ns, poly_elem, cell)
    return etree.tostring(kml, pretty_print=True, xml_declaration=True, encoding="UTF-8").decode("utf-8")

# -------------------------------------------------
# PDF report builder (final)
# -------------------------------------------------
def build_pdf_report_standard(cells_ll, merged_ll, user_inputs, cell_size, overlay_present):
    """Creates clean PDF report with fixed encoding + Streamlit-safe bytes output"""
    font_path = os.path.join(os.path.dirname(__file__), "DejaVuSans.ttf")
    if not os.path.exists(font_path):
        try:
            url = "https://github.com/dejavu-fonts/dejavu-fonts/raw/version_2_37/ttf/DejaVuSans.ttf"
            r = requests.get(url, timeout=10)
            with open(font_path, "wb") as f:
                f.write(r.content)
        except Exception:
            st.warning("⚠️ Font download failed — using Helvetica fallback")

    pdf = FPDF("P", "mm", "A4")
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()

    if os.path.exists(font_path):
        pdf.add_font("DejaVu", "", font_path)
        pdf.add_font("DejaVu", "B", font_path)
        pdf.add_font("DejaVu", "I", font_path)
        pdf.set_font("DejaVu", "B", 14)
    else:
        pdf.set_font("Helvetica", "B", 14)

    pdf.cell(0, 8, "KML GRID GENERATOR v3.0 - FIELD REPORT", ln=1, align="C")
    pdf.ln(3)
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "", 11)
    pdf.cell(0, 6, f"Range: {user_inputs.get('range_name','')} | RF: {user_inputs.get('rf_name','')}", ln=1)
    pdf.cell(0, 6, f"Beat: {user_inputs.get('beat_name','')} | Year: {user_inputs.get('year_of_work','')}", ln=1)
    pdf.ln(3)

    centroid = merged_ll.centroid
    utm = utm_crs_for_lonlat(centroid.x, centroid.y)
    total_area = 0
    rows = []
    for i, geom in enumerate(cells_ll, 1):
        area_m2 = gpd.GeoSeries([geom], crs=4326).to_crs(utm).area.iloc[0]
        area_ha = float(area_m2) / 10000
        rows.append((i, area_ha, geom.centroid.y, geom.centroid.x))
        total_area += area_ha

    pdf.set_font("DejaVu", "B", 12)
    pdf.cell(0, 7, "Summary", ln=1)
    pdf.set_font("DejaVu", "", 11)
    pdf.cell(0, 6, f"Total Cells: {len(rows)} | Total Area: {total_area:.2f} ha", ln=1)
    pdf.cell(0, 6, f"Cell Size: {cell_size} m | Overlay: {'Yes' if overlay_present else 'No'}", ln=1)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%d-%b-%Y %H:%M')}", ln=1)
    pdf.ln(4)

    pdf.set_font("DejaVu", "B", 11)
    pdf.cell(25, 8, "Grid #", border=1, align="C")
    pdf.cell(35, 8, "Area (ha)", border=1, align="C")
    pdf.cell(65, 8, "Lat", border=1, align="C")
    pdf.cell(65, 8, "Lon", border=1, align="C")
    pdf.ln(8)

    pdf.set_font("DejaVu", "", 10)
    for i, a, lat, lon in rows:
        pdf.cell(25, 7, str(i), border=1)
        pdf.cell(35, 7, f"{a:.2f}", border=1, align="R")
        pdf.cell(65, 7, f"{lat:.6f}", border=1, align="R")
        pdf.cell(65, 7, f"{lon:.6f}", border=1, align="R")
        pdf.ln(7)

    pdf.ln(4)
    pdf.set_font("DejaVu", "I", 9)
    pdf.multi_cell(0, 5, "Note: Areas computed in UTM projection for accuracy.\nReport generated by KML Grid Generator v3.0 - Rasipuram Range.")

    result = pdf.output(dest="S")
    if isinstance(result, bytearray):
        return bytes(result)
    elif isinstance(result, bytes):
        return result
    elif isinstance(result, str):
        return result.encode("latin-1", errors="ignore")
    else:
        raise TypeError(f"Unexpected PDF output type: {type(result)}")

# -------------------------------------------------
# Sidebar Inputs
# -------------------------------------------------
st.sidebar.header("⚙️ Options")
uploaded_aoi = st.sidebar.file_uploader("Upload AOI (KML/KMZ)", type=["kml", "kmz"])
overlay_file = st.sidebar.file_uploader("Optional Overlay", type=["kml", "kmz"])
cell_size = st.sidebar.number_input("Grid cell size (m)", 10, 2000, 100, 10)
range_name = st.sidebar.text_input("Range Name", "Thammampatti")
rf_name = st.sidebar.text_input("RF Name", "Karumalai")
beat_name = st.sidebar.text_input("Beat Name", "A1")
year_of_work = st.sidebar.text_input("Year of Work", "2024")

if st.sidebar.button("➕ Add Input Labels"):
    st.session_state["user_inputs"] = {
        "range_name": range_name,
        "rf_name": rf_name,
        "beat_name": beat_name,
        "year_of_work": year_of_work
    }
    st.sidebar.success("✅ Label inputs added.")

generate_pdf = st.sidebar.checkbox("📄 Generate PDF Report", True)
col_btn1, col_btn2 = st.sidebar.columns(2)
with col_btn1: generate_click = st.button("▶ Generate Grid")
with col_btn2: reset_click = st.button("🔄 Reset Map")
if reset_click: st.session_state.clear(); init_state(); st.rerun()
if generate_click: st.session_state["generated"] = True

# -------------------------------------------------
# Main UI
# -------------------------------------------------
if st.session_state["generated"]:
    m = folium.Map(location=[11.0, 78.5], zoom_start=8)
    bounds, overlay_gdf, cells_ll, merged_ll = None, None, [], None

    if uploaded_aoi:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".kml") as tmp:
            tmp.write(uploaded_aoi.read())
            tmp_path = tmp.name
        gdf = gpd.read_file(tmp_path, driver="KML")
        polygons = gdf.geometry
        cells_ll, merged_ll = make_grid_exact_clipped(polygons, cell_size)
        aoi_union = unary_union(polygons)
        folium.GeoJson(mapping(aoi_union), name="AOI", style_function=lambda x: {"color": "red", "weight": 1}).add_to(m)
        for c in cells_ll:
            folium.GeoJson(mapping(c), style_function=lambda x: {"color": "red", "weight": 1}).add_to(m)
        minx, miny, maxx, maxy = aoi_union.bounds
        bounds = [[miny, minx], [maxy, maxx]]

    if overlay_file:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".kml") as tmp:
            tmp.write(overlay_file.read())
            tmp_path = tmp.name
        overlay_gdf = gpd.read_file(tmp_path, driver="KML")
        for geom in overlay_gdf.geometry:
            if not geom.is_empty:
                folium.GeoJson(mapping(geom), style_function=lambda x: {"color": "#FFD700", "weight": 3}).add_to(m)
        if bounds is None and not overlay_gdf.empty:
            minx, miny, maxx, maxy = overlay_gdf.total_bounds
            bounds = [[miny, minx], [maxy, maxx]]

    if bounds: m.fit_bounds(bounds)
    st_folium(m, width=1200, height=700)

    if uploaded_aoi:
        user_inputs = st.session_state["user_inputs"]
        st.success(f"✅ Generated {len(cells_ll)} grid cells inside AOI.")
        grid_kml = generate_grid_only_kml(cells_ll, merged_ll)
        labeled_kml = generate_labeled_kml(cells_ll, merged_ll, user_inputs, overlay_gdf)

        st.markdown("### 💾 Downloads")
        col1, col2, col3 = st.columns(3)
        with col1:
            st.download_button("📦 Download Grid Only KML", grid_kml, "grid_only.kml", "application/vnd.google-earth.kml+xml")
        with col2:
            st.download_button("🧾 Download Labeled + Merged KML", labeled_kml, "merged_labeled.kml", "application/vnd.google-earth.kml+xml")
        with col3:
            if generate_pdf:
                pdf_bytes = build_pdf_report_standard(cells_ll, merged_ll, user_inputs, cell_size, overlay_file is not None)
                st.download_button("📄 Download Report (PDF)", pdf_bytes, "grid_report.pdf", "application/pdf")
    else:
        st.info("✅ Overlay loaded (no AOI provided).")
else:
    st.info("👆 Upload AOI, click ➕ Add Input Labels, then ▶ Generate Grid.")
