import streamlit as st
import geopandas as gpd
from shapely.geometry import box
from shapely.ops import unary_union
from pyproj import CRS
import math
from lxml import etree
from shapely.geometry import mapping
from streamlit_folium import st_folium
import folium
import tempfile
from fpdf import FPDF
from datetime import datetime
import os
import requests

# ----------------------------------------------------------------------
# 🔧 Initial Streamlit setup
# ----------------------------------------------------------------------
st.set_page_config(page_title="KML to Grid Generator v3.0", layout="wide")
st.title("🗺️ KML to Grid Generator v3.0")

# ----------------------------------------------------------------------
# 🧩 Initialize State
# ----------------------------------------------------------------------
def init_state():
    if "user_inputs" not in st.session_state:
        st.session_state["user_inputs"] = {
            "range_name": "",
            "rf_name": "",
            "beat_name": "",
            "year_of_work": ""
        }
    if "generated" not in st.session_state:
        st.session_state["generated"] = False

init_state()

# ----------------------------------------------------------------------
# 🧭 Helper — Determine UTM zone for given lon/lat
# ----------------------------------------------------------------------
def utm_crs_for_lonlat(lon, lat):
    zone = int((lon + 180) / 6) + 1
    epsg = 32600 + zone if lat >= 0 else 32700 + zone
    return CRS.from_epsg(epsg)

# ----------------------------------------------------------------------
# 🧱 Generate grid inside AOI
# ----------------------------------------------------------------------
def make_grid_exact_clipped(polygons_ll, cell_size_m=100):
    merged_ll = unary_union(polygons_ll)
    centroid = merged_ll.centroid
    utm = utm_crs_for_lonlat(centroid.x, centroid.y)

    merged_utm = gpd.GeoSeries([merged_ll], crs="EPSG:4326").to_crs(utm)
    minx, miny, maxx, maxy = merged_utm.total_bounds

    cols = int(math.ceil((maxx - minx) / cell_size_m))
    rows = int(math.ceil((maxy - miny) / cell_size_m))

    cells = []
    aoi_union = merged_utm.unary_union
    for i in range(cols):
        for j in range(rows):
            x0 = minx + i * cell_size_m
            y0 = miny + j * cell_size_m
            cell = box(x0, y0, x0 + cell_size_m, y0 + cell_size_m)
            if aoi_union.intersects(cell):
                inter = cell.intersection(aoi_union)
                if not inter.is_empty:
                    cells.append(inter)

    # back to WGS84 for export/preview
    cells_ll = [gpd.GeoSeries([geom], crs=utm).to_crs(4326).iloc[0] for geom in cells]
    return cells_ll, merged_ll

# ----------------------------------------------------------------------
# ✏️ KML Writing Helpers
# ----------------------------------------------------------------------
def _ring_coords_to_kml(ring):
    return " ".join([f"{pt[0]},{pt[1]},0" for pt in ring.coords if len(pt) >= 2])

def _write_polygon_coords(ns, parent_polygon_elem, geom):
    def write_one(poly):
        outer = etree.SubElement(parent_polygon_elem, "{%s}outerBoundaryIs" % ns)
        lr_out = etree.SubElement(outer, "{%s}LinearRing" % ns)
        etree.SubElement(lr_out, "{%s}coordinates" % ns).text = _ring_coords_to_kml(poly.exterior)
        for hole in getattr(poly, "interiors", []):
            inner = etree.SubElement(parent_polygon_elem, "{%s}innerBoundaryIs" % ns)
            lr_in = etree.SubElement(inner, "{%s}LinearRing" % ns)
            etree.SubElement(lr_in, "{%s}coordinates" % ns).text = _ring_coords_to_kml(hole)
    if geom.geom_type == "Polygon":
        write_one(geom)
    elif geom.geom_type == "MultiPolygon":
        for part in geom.geoms:
            poly_elem = etree.SubElement(parent_polygon_elem.getparent(), "{%s}Polygon" % ns)
            write_one(part)

# ----------------------------------------------------------------------
# 🧾 Generate labeled KML
# ----------------------------------------------------------------------
def generate_labeled_kml(cells_ll, merged_ll, user_inputs, overlay_gdf=None):
    ns = "http://www.opengis.net/kml/2.2"
    kml = etree.Element("{%s}kml" % ns)
    doc = etree.SubElement(kml, "{%s}Document" % ns)
    etree.SubElement(doc, "{%s}name" % ns).text = "Labeled Grid"
    etree.SubElement(doc, "{%s}description" % ns).text = "Generated by Rasipuram Range"

    style = etree.SubElement(doc, "{%s}Style" % ns, id="gridStyle")
    ls = etree.SubElement(style, "{%s}LineStyle" % ns)
    etree.SubElement(ls, "{%s}color" % ns).text = "ff0000ff"
    etree.SubElement(ls, "{%s}width" % ns).text = "1"
    ps = etree.SubElement(style, "{%s}PolyStyle" % ns)
    etree.SubElement(ps, "{%s}fill" % ns).text = "0"

    for i, cell in enumerate(cells_ll, start=1):
        pm = etree.SubElement(doc, "{%s}Placemark" % ns)
        etree.SubElement(pm, "{%s}name" % ns).text = f"{i}"
        etree.SubElement(pm, "{%s}styleUrl" % ns).text = "#gridStyle"
        poly_elem = etree.SubElement(pm, "{%s}Polygon" % ns)
        _write_polygon_coords(ns, poly_elem, cell)

    return etree.tostring(kml, pretty_print=True, xml_declaration=True, encoding="UTF-8").decode("utf-8")

# ----------------------------------------------------------------------
# 📄 PDF REPORT GENERATOR
# ----------------------------------------------------------------------
def build_pdf_report_standard(cells_ll, merged_ll, user_inputs, cell_size, overlay_present,
                              title_text, density, area_invasive):
    centroid = merged_ll.centroid
    minx, miny, maxx, maxy = merged_ll.bounds

    sat_url = f"https://static-maps.yandex.ru/1.x/?lang=en_US&ll={(minx+maxx)/2},{(miny+maxy)/2}&z=14&l=sat&size=650,450"
    tmp_dir = tempfile.gettempdir()
    map_image_path = os.path.join(tmp_dir, "aoi_satellite.png")
    try:
        r = requests.get(sat_url, timeout=15)
        with open(map_image_path, "wb") as f:
            f.write(r.content)
    except Exception:
        map_image_path = None

    pdf = FPDF("P", "mm", "A4")
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()

    font_path = os.path.join(os.path.dirname(__file__), "DejaVuSans.ttf")
    if not os.path.exists(font_path):
        try:
            url = "https://raw.githubusercontent.com/dejavu-fonts/dejavu-fonts/master/ttf/DejaVuSans.ttf"
            r = requests.get(url, timeout=15)
            with open(font_path, "wb") as f:
                f.write(r.content)
        except Exception:
            pass

    if os.path.exists(font_path):
        pdf.add_font("DejaVu", "", font_path, uni=True)
        pdf.add_font("DejaVu", "B", font_path, uni=True)
        pdf.add_font("DejaVu", "I", font_path, uni=True)
        pdf.set_font("DejaVu", "B", 14)
    else:
        pdf.set_font("Helvetica", "B", 14)

    pdf.cell(0, 8, "KML GRID GENERATOR v3.0 - FIELD REPORT", ln=1, align="C")
    pdf.ln(3)

    if map_image_path and os.path.exists(map_image_path):
        pdf.image(map_image_path, x=15, y=25, w=180)
        pdf.ln(95)
    else:
        pdf.ln(100)

    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "", 11)
    legend_lines = [
        f"Range: {user_inputs.get('range_name','')}",
        f"RF: {user_inputs.get('rf_name','')}",
        f"Beat: {user_inputs.get('beat_name','')}",
        f"Density: {density}",
        f"Area of Invasive: {area_invasive} Ha",
        f"Grid Size: {cell_size} m",
        f"Overlay Included: {'Yes' if overlay_present else 'No'}",
        f"Generated: {datetime.now().strftime('%d-%b-%Y %H:%M')}"
    ]
    for line in legend_lines:
        pdf.cell(0, 6, line, ln=1)

    pdf.ln(4)
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "I", 9)
    pdf.multi_cell(0, 5, "Note: Satellite map automatically fetched. Report generated by KML Grid Generator v3.0.")

    result = pdf.output(dest="S")
    if isinstance(result, bytearray):
        result = bytes(result)
    elif isinstance(result, str):
        result = result.encode("latin1", errors="ignore")
    return result

# ----------------------------------------------------------------------
# 🧰 SIDEBAR UI
# ----------------------------------------------------------------------
st.sidebar.header("⚙️ Options")

uploaded_aoi = st.sidebar.file_uploader("Upload AOI KML/KMZ", type=["kml", "kmz"])
overlay_file = st.sidebar.file_uploader("Optional Overlay KML/KMZ", type=["kml", "kmz"])
cell_size = st.sidebar.number_input("Grid cell size (meters)", min_value=10, max_value=2000, value=100, step=10)

range_name = st.sidebar.text_input("Range Name", "Thammampatty")
rf_name = st.sidebar.text_input("RF Name", "Paithur RF")
beat_name = st.sidebar.text_input("Beat Name", "Paithur South")
year_of_work = st.sidebar.text_input("Year of Work", "2024")
title_text = st.sidebar.text_input("🧭 Report Title", "Removal of Invasive Species, Thammampatty Range")
density = st.sidebar.text_input("Density", "Medium")
area_invasive = st.sidebar.text_input("Area of Invasive (Ha)", "5")

if st.sidebar.button("➕ Add Input Labels"):
    st.session_state["user_inputs"] = {
        "range_name": range_name,
        "rf_name": rf_name,
        "beat_name": beat_name,
        "year_of_work": year_of_work
    }
    st.sidebar.success("✅ Label inputs added.")

generate_pdf = st.sidebar.checkbox("📄 Generate PDF Report", value=True)

col_btn1, col_btn2 = st.sidebar.columns(2)
with col_btn1:
    generate_click = st.button("▶ Generate Grid")
with col_btn2:
    reset_click = st.button("🔄 Reset Map")

if reset_click:
    st.session_state.clear()
    init_state()
    st.experimental_rerun()

if generate_click:
    st.session_state["generated"] = True

# ----------------------------------------------------------------------
# 🗺️ MAIN AREA
# ----------------------------------------------------------------------
if st.session_state["generated"]:
    m = folium.Map(location=[11.0, 78.5], zoom_start=8)
    bounds = None
    overlay_gdf = None
    cells_ll = []
    merged_ll = None

    if uploaded_aoi is not None:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".kml") as tmp:
            tmp.write(uploaded_aoi.read())
            tmp_path = tmp.name
        gdf = gpd.read_file(tmp_path, driver="KML")
        polygons = gdf.geometry
        cells_ll, merged_ll = make_grid_exact_clipped(polygons, cell_size)
        aoi_union = unary_union(polygons)

        folium.GeoJson(mapping(aoi_union), name="AOI",
                       style_function=lambda x: {"color": "red", "weight": 1, "fillOpacity": 0}).add_to(m)
        for cell in cells_ll:
            folium.GeoJson(mapping(cell), name="Grid",
                           style_function=lambda x: {"color": "yellow", "weight": 1, "fillOpacity": 0}).add_to(m)

        minx, miny, maxx, maxy = aoi_union.bounds
        bounds = [[miny, minx], [maxy, maxx]]

    if overlay_file is not None:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".kml") as tmp2:
            tmp2.write(overlay_file.read())
            tmp2_path = tmp2.name
        overlay_gdf = gpd.read_file(tmp2_path, driver="KML")
        for geom in overlay_gdf.geometry:
            if geom.is_empty:
                continue
            folium.GeoJson(mapping(geom), name="Overlay",
                           style_function=lambda x: {"color": "#FFD700", "weight": 3, "fillOpacity": 0}).add_to(m)
        if bounds is None and not overlay_gdf.empty:
            minx, miny, maxx, maxy = overlay_gdf.total_bounds
            bounds = [[miny, minx], [maxy, maxx]]

    if bounds:
        m.fit_bounds(bounds)

    st_folium(m, width=1200, height=700)

    if uploaded_aoi is not None:
        user_inputs = st.session_state["user_inputs"]
        grid_count = len(cells_ll)
        total_area_ha = sum([c.area * (111000 ** 2) / 10000 for c in cells_ll])
        st.success(f"✅ Generated {grid_count} grid cells covering approximately {total_area_ha:.2f} ha inside AOI")

        grid_kml = generate_labeled_kml(cells_ll, merged_ll, user_inputs, overlay_gdf)
        st.markdown("### 💾 Downloads")
        col1, col2, col3 = st.columns(3)
        with col1:
            st.download_button("📦 Download Grid + Labels (KML)", grid_kml,
                               file_name="grid.kml", mime="application/vnd.google-earth.kml+xml")
        with col3:
            if generate_pdf:
                pdf_bytes = build_pdf_report_standard(
                    cells_ll, merged_ll, user_inputs, cell_size,
                    overlay_file is not None, title_text, density, area_invasive
                )
                st.download_button("📄 Download Report (PDF)", pdf_bytes,
                                   file_name="grid_report.pdf", mime="application/pdf")
else:
    st.info("👆 Upload AOI, set labels, then press ▶ Generate Grid.")
