import requests
from io import BytesIO
from fpdf import FPDF
import os
from datetime import datetime
import streamlit as st
import geopandas as gpd

def build_pdf_report_standard(cells_ll, merged_ll, user_inputs, cell_size, overlay_present):
    """Create a standard A4 PDF with header, summary, and cell table — fully Streamlit-safe."""

    # ✅ Create temp font path
    temp_font_path = os.path.join(os.path.dirname(__file__), "DejaVuSans.ttf")

    # ✅ Auto-download DejaVu font if missing
    if not os.path.exists(temp_font_path):
        try:
            st.info("📥 Downloading DejaVuSans.ttf font...")
            url = "https://github.com/dejavu-fonts/dejavu-fonts/raw/version_2_37/ttf/DejaVuSans.ttf"
            r = requests.get(url, timeout=20)
            if r.status_code == 200:
                with open(temp_font_path, "wb") as f:
                    f.write(r.content)
                st.success("✅ DejaVuSans.ttf downloaded successfully.")
            else:
                st.warning("⚠️ Could not download DejaVuSans.ttf — using fallback font.")
        except Exception as e:
            st.warning(f"⚠️ Font download failed: {e}. Using fallback Helvetica font.")

    # ✅ Initialize PDF
    pdf = FPDF("P", "mm", "A4")
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()

    # ✅ Load DejaVu or fallback to Helvetica
    if os.path.exists(temp_font_path):
        pdf.add_font("DejaVu", "", temp_font_path)
        pdf.add_font("DejaVu", "B", temp_font_path)
        pdf.add_font("DejaVu", "I", temp_font_path)
        pdf.set_font("DejaVu", "B", 14)
    else:
        pdf.set_font("Helvetica", "B", 14)

    # === HEADER ===
    pdf.cell(0, 8, "KML GRID GENERATOR v3.0 - FIELD REPORT", ln=1, align="C")
    pdf.ln(3)

    # === RANGE INFO ===
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "", 11)
    pdf.cell(0, 6, f"Range: {user_inputs.get('range_name','')} | RF: {user_inputs.get('rf_name','')}", ln=1)
    pdf.cell(0, 6, f"Beat: {user_inputs.get('beat_name','')} | Year: {user_inputs.get('year_of_work','')}", ln=1)
    pdf.ln(3)

    # === SUMMARY ===
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "B", 12)
    pdf.cell(0, 7, "Summary", ln=1)
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "", 11)

    # Compute total area
    centroid = merged_ll.centroid
    from pyproj import CRS
    utm = CRS.from_epsg(32600 + int((centroid.x + 180) / 6) + (0 if centroid.y >= 0 else 100))
    rows = []
    total_area = 0.0
    for i, geom in enumerate(cells_ll, start=1):
        area_m2 = gpd.GeoSeries([geom], crs=4326).to_crs(utm).area.iloc[0]
        area_ha = float(area_m2) / 10000.0
        rows.append((i, area_ha, geom.centroid.y, geom.centroid.x))
        total_area += area_ha

    pdf.cell(0, 6, f"Total Cells: {len(rows)} | Total Area: {total_area:.2f} ha", ln=1)
    pdf.cell(0, 6, f"Cell Size: {cell_size} m | Overlay Included: {'Yes' if overlay_present else 'No'}", ln=1)
    pdf.cell(0, 6, f"Generated on: {datetime.now().strftime('%d-%b-%Y %H:%M')}", ln=1)
    pdf.ln(3)

    # === TABLE HEADER ===
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "B", 11)
    pdf.cell(25, 8, "Grid #", border=1, align="C")
    pdf.cell(35, 8, "Area (ha)", border=1, align="C")
    pdf.cell(65, 8, "Centroid Lat", border=1, align="C")
    pdf.cell(65, 8, "Centroid Lon", border=1, align="C")
    pdf.ln(8)

    # === TABLE BODY ===
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "", 10)
    for idx, area, lat, lon in rows:
        pdf.cell(25, 7, str(idx), border=1)
        pdf.cell(35, 7, f"{area:.2f}", border=1, align="R")
        pdf.cell(65, 7, f"{lat:.6f}", border=1, align="R")
        pdf.cell(65, 7, f"{lon:.6f}", border=1, align="R")
        pdf.ln(7)

    # === FOOTER NOTE ===
    pdf.ln(4)
    pdf.set_font("DejaVu" if "DejaVu" in pdf.fonts else "Helvetica", "I", 9)
    pdf.multi_cell(
        0, 5,
        "Note: Areas computed using UTM for better accuracy.\n"
        "Report generated by KML Grid Generator v3.0 - Rasipuram Range."
    )

    # ✅ Return valid bytes for Streamlit
    result = pdf.output(dest="S")
    if isinstance(result, bytearray):
        return bytes(result)
    elif isinstance(result, bytes):
        return result
    elif isinstance(result, str):
        return result.encode("latin-1", errors="ignore")
    else:
        raise TypeError(f"Unexpected PDF output type: {type(result)}")
